name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      tag: 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi


  last:
    runs-on: ubuntu-latest

    steps:
    - run: echo "the end"
