name: My reusable

on:
  workflow_call:
    inputs:
      tag: 
        type: string

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current version
        id: current_version
        run: echo "::set-output name=current-version::$(cat version.json | jq -r '.version')"
        
      - name: Get last commit
        id: last_commit
        run: echo "::set-output name=last-commit::$(git rev-list -n 1 HEAD -- version.json)"
        if: github.event_name == 'push'
        
      - name: Get last version
        id: last_version
        run: echo "::set-output name=last-version::$(git show ${{ steps.last_commit.outputs.last-commit }}:version.json | jq -r '.version')"
        if: steps.last_commit.outputs.last-commit != ''
        
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ steps.last_version.outputs.last-version }}" != "${{ steps.current_version.outputs.current-version }}" ]; then
            echo "Version file has changed"
          else
            echo "Version file has not changed"
            exit 1
          fi

  building:
     runs-on: ubuntu-latest
     
     steps:
      - name: start build
        run: echo building!!!
