name: My reusable

on:
  workflow_call:
    inputs:
      tag: 
        type: string

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Get last version
      id: last-version
      run: |
        last_version=$(jq -r '.version' file.json)
        echo "::set-output name=last_version::$last_version"
    - name: Check version
      run: |
        version=$(jq -r '.version' file.json)
        last_version=${{ steps.last-version.outputs.last_version }}
        if [[ "$version" != "$last_version" ]]; then
          echo "Incorrect version found: $version (last version: $last_version)"
          exit 1
        fi

  building:
     runs-on: ubuntu-latest
     needs: [check_version]
     
     steps:
      - name: start build
        run: echo building!!!
