name: My reusable

on:
  workflow_call:
    inputs:
      main_branch: 
        type: string
      file: 
        type: string
      key: 
        type: string

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Get current version
      id: get_latest_version
      run: |
        latest_version=$(jq -r '.version' version.json)
        echo "::set-output name=latest_version::$current_version"
    - name: Checkout PR code
      uses: actions/checkout@v2
    - name: Get updated version
      id: get_current_version
      run: |
        current_version=$(jq -r '.version' version.json)
        echo "::set-output name=current_version::$current_version"
    - name: Compare versions
      run: |
        current_version=${{ steps.get_current_version.outputs.current_version }}
        latest_version=${{ steps.get_latest_version.outputs.latest_version }}
        if [ "$(printf '%s\n' "$latest_version" "$current_version" | sort -V | head -n1)" = "$current_version" ]; then
          echo "Current version ($current_version) is greater than the latest version ($latest_version)"
        else
          echo "Current version ($current_version) is not greater than the latest version ($latest_version)"
          exit 1
        fi
