name: My reusable

on:
  workflow_call:
    inputs:
      tag: 
        type: string

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read previous version
        id: read_version
        run: echo "::set-output name=version::$(cat version.json | jq -r '.version')"

      - name: Read current version
        id: read_new_version
        run: echo "::set-output name=new_version::$(cat version.json | jq -r '.version')"
        
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ steps.read_version.outputs.version }}" != "${{ steps.read_new_version.outputs.new_version }}" ]; then
            echo "Version file has changed"
          else
            echo "Version file has not changed"
            exit 1
          fi
