name: My reusable

on:
  workflow_call:
    inputs:
      tag: 
        type: string

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare version
        run: |
          FILE_TO_COMPARE="version.json"
          JSON_KEY="version"
          MAIN_VALUE=$(jq -r ".$JSON_KEY" origin/main $FILE_TO_COMPARE)
          FEATURE_VALUE=$(jq -r ".$JSON_KEY" HEAD $FILE_TO_COMPARE)
          if [ "$MAIN_VALUE" == "$FEATURE_VALUE" ]; then
            echo "Version was not  updated."
            exit 1
          fi

  building:
     runs-on: ubuntu-latest
     needs: [check_version]
     
     steps:
      - name: start build
        run: echo building!!!
