name: Verify and validate version from version file

on:
  workflow_call:
    inputs:
      main-branch: 
        description: 'main/trunk branch name'
        required: false
        default: 'main'
        type: string
      file-name: 
        description: 'Name file that contains version'
        required: false
        default: 'VERSION'
        type: string
    outputs:
      current-version:
        description: ""
        value: ${{ jobs.verify_version.outputs.current_version }}

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout version from main-branch code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.main-branch }}
    - name: Get latest version
      id: get_latest_version
      run: echo "latest_version=$(cat VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT
    - name: Checkout version from PR code
      uses: actions/checkout@v3
    - name: Get current version
      id: get_current_version
      run: echo "current_version=$(cat VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT
    - name: Validate current version
      run: |
        current_version=${{ steps.get_current_version.outputs.current_version }}
        
        if ! [[ $current_version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+(\.[0-9]+)*)?(\+[0-9]+(\.[0-9]+)*)?$ ]]; then
          echo "Error: ($current_version) is not a valid semver."
          exit 1
        fi
    - name: Verify and Compare versions
      run: |
        current_version=${{ steps.get_current_version.outputs.current_version }}
        latest_version=${{ steps.get_latest_version.outputs.latest_version }}
        
        if [ $(echo -e "${current_version}\n${latest_version}"|sort -V|head -1) != "${current_version}" ]; then
          echo "Current version ($current_version) is greater than the latest version ($latest_version)"
        else
          echo "Current version ($current_version) is not greater than the latest version ($latest_version)"
          exit 1
        fi
